# Generated by Django 6.1.1 on 2026-09-20 01:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, verbose_name='id del lote en el acreedor')),
                ('cut_off', models.DateField(verbose_name='fecha de corte')),
                ('source', models.CharField(choices=[('api', 'Por API'), ('file', 'Archivo cargado a mano')], default='api', max_length=10, verbose_name='origen')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processed', 'Procesado'), ('rejected', 'Rechazado')], default='received', max_length=20, verbose_name='estado')),
                ('received_count', models.PositiveIntegerField(default=0, verbose_name='deudas recibidas')),
                ('accepted_count', models.PositiveIntegerField(default=0, verbose_name='aceptadas')),
                ('rejected_count', models.PositiveIntegerField(default=0, verbose_name='rechazadas')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='huella del contenido')),
                ('response', models.JSONField(blank=True, default=dict, help_text='Lo que se le contesto al acreedor. Un reenvio identico recibe esto mismo en vez de procesarse de nuevo.', verbose_name='respuesta entregada')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
                ('campaign', models.ForeignKey(blank=True, db_column='campaign_id', help_text='Se asigna despues de recibir, al armar la campana.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='crm.campaign', verbose_name='campana')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='crm.creditor', verbose_name='acreedor')),
            ],
            options={
                'verbose_name': 'entrega recibida',
                'verbose_name_plural': 'entregas recibidas',
                'db_table': 'cartera_batch',
                'ordering': ['-cut_off', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, verbose_name='id en el acreedor')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='moneda')),
                ('concept', models.CharField(max_length=200, verbose_name='concepto')),
                ('refs', models.JSONField(blank=True, default=dict, help_text='Lo que se le muestra al deudor para que reconozca la deuda.', verbose_name='referencias')),
                ('status', models.CharField(choices=[('open', 'En gestion'), ('paid', 'Pagada'), ('withdrawn', 'Retirada por el acreedor'), ('disputed', 'Disputada')], default='open', max_length=20, verbose_name='estado')),
                ('withdrawn_reason', models.CharField(blank=True, max_length=30, null=True, verbose_name='motivo del retiro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='crm.creditor', verbose_name='acreedor')),
                ('first_batch', models.ForeignKey(db_column='first_batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='debts_opened', to='cartera.batch', verbose_name='entrega que la trajo')),
                ('last_batch', models.ForeignKey(db_column='last_batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='debts_updated', to='cartera.batch', verbose_name='ultima entrega')),
            ],
            options={
                'verbose_name': 'deuda',
                'verbose_name_plural': 'deudas',
                'db_table': 'cartera_debt',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=120, verbose_name='concepto')),
                ('period', models.CharField(blank=True, max_length=7, null=True, verbose_name='periodo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('due_date', models.DateField(verbose_name='vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('debt', models.ForeignKey(db_column='debt_id', on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cartera.debt', verbose_name='deuda')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'db_table': 'cartera_debtcharge',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(help_text='Normalizado, sin puntos y con guion: 16482337-7', max_length=12, unique=True, verbose_name='RUT')),
                ('kind', models.CharField(choices=[('person', 'Persona'), ('company', 'Empresa')], default='person', max_length=10, verbose_name='tipo')),
                ('full_name', models.CharField(max_length=160, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'deudor',
                'verbose_name_plural': 'deudores',
                'db_table': 'cartera_debtor',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['person', 'company'])), name='ck_debtor_kind'), models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False), _connector='OR'), name='ck_debtor_contacto')],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(db_column='debtor_id', on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='cartera.debtor', verbose_name='deudor'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('creditor', 'external_id'), name='uq_batch_external'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['api', 'file'])), name='ck_batch_source'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['received', 'processed', 'rejected'])), name='ck_batch_status'),
        ),
        migrations.AddIndex(
            model_name='debtcharge',
            index=models.Index(fields=['debt', 'due_date'], name='ix_charge_debt_due'),
        ),
        migrations.AddConstraint(
            model_name='debtcharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_charge_amount'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['creditor', 'status'], name='ix_debt_creditor_status'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.UniqueConstraint(fields=('creditor', 'external_id'), name='uq_debt_external'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['CLP', 'UF'])), name='ck_debt_currency'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'paid', 'withdrawn', 'disputed'])), name='ck_debt_status'),
        ),
    ]
