# Generated by Django 6.1.1 on 2026-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='debtor',
            constraint=models.CheckConstraint(condition=models.Q(('tax_id__regex', '^[0-9]{7,8}-[0-9K]$')), name='ck_debtor_tax_id'),
        ),
    ]
