# Generated by Django 6.1.1 on 2026-09-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_debtor_ck_debtor_tax_id'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='debt',
            name='ck_debt_status',
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('open', 'En gestion'), ('repacted', 'En convenio de pago'), ('paid', 'Pagada'), ('withdrawn', 'Retirada por el acreedor'), ('disputed', 'Disputada')], default='open', max_length=20, verbose_name='estado'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'repacted', 'paid', 'withdrawn', 'disputed'])), name='ck_debt_status'),
        ),
    ]
