# Generated by Django 6.1.1 on 2026-09-20 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Para que se emitio.', max_length=80, verbose_name='nombre')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='huella de la clave')),
                ('prefix', models.CharField(max_length=12, verbose_name='prefijo visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='emitida')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revocada')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='crm.creditor', verbose_name='acreedor')),
            ],
            options={
                'verbose_name': 'clave de API',
                'verbose_name_plural': 'claves de API',
                'db_table': 'integracion_apikey',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='ix_apikey_hash')],
            },
        ),
    ]
