# Generated by Django 6.1.1 on 2026-09-22 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from crm.operaciones import SiFalta


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_debtor_ck_debtor_tax_id'),
        ('integracion', '0001_initial'),
    ]

    operations = [
        SiFalta(migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True, verbose_name='id del lote hacia DataBridge')),
                ('status', models.CharField(choices=[('pending', 'Por enviar'), ('waiting', 'Esperando campana'), ('sent', 'Entregada'), ('failed', 'Fallida')], default='pending', max_length=10, verbose_name='estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='proximo intento')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='entregada')),
                ('last_error', models.CharField(blank=True, max_length=300, null=True, verbose_name='ultimo error')),
                ('response', models.JSONField(blank=True, default=dict, verbose_name='respuesta de DataBridge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('batch', models.OneToOneField(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='forward', to='cartera.batch', verbose_name='entrega recibida')),
            ],
            options={
                'verbose_name': 'reenvio a DataBridge',
                'verbose_name_plural': 'reenvios a DataBridge',
                'db_table': 'integracion_forward',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='ix_forward_por_enviar')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'waiting', 'sent', 'failed'])), name='ck_forward_status')],
            },
        )),
    ]
