# Generated by Django 6.1.1 on 2026-09-22 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from crm.operaciones import SiFalta


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0003_debt_repacted'),
        ('crm', '0001_initial'),
        ('integracion', '0002_forward'),
    ]

    operations = [
        SiFalta(migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True, verbose_name='id del evento')),
                ('type', models.CharField(max_length=30, verbose_name='tipo')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='ocurrido')),
                ('payload', models.JSONField(verbose_name='evento recibido')),
                ('result', models.CharField(max_length=80, verbose_name='resultado')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
                ('debt', models.ForeignKey(blank=True, db_column='debt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cartera.debt', verbose_name='deuda')),
            ],
            options={
                'verbose_name': 'evento recibido',
                'verbose_name_plural': 'eventos recibidos',
                'db_table': 'integracion_inboundevent',
                'ordering': ['-received_at'],
            },
        )),
        SiFalta(migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('secret', models.CharField(max_length=120, verbose_name='secreto')),
                ('events', models.JSONField(blank=True, default=list, help_text='Vacio = todos.', verbose_name='eventos')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='crm.creditor', verbose_name='acreedor')),
            ],
            options={
                'verbose_name': 'suscripcion de un cliente',
                'verbose_name_plural': 'suscripciones de clientes',
                'db_table': 'integracion_subscription',
            },
        )),
        SiFalta(migrations.CreateModel(
            name='OutboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, verbose_name='id del evento')),
                ('type', models.CharField(max_length=30, verbose_name='tipo')),
                ('payload', models.JSONField(verbose_name='evento')),
                ('status', models.CharField(choices=[('pending', 'Por enviar'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=10, verbose_name='estado')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='proximo intento')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregado')),
                ('last_error', models.CharField(blank=True, max_length=300, null=True, verbose_name='ultimo error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('origin', models.ForeignKey(blank=True, db_column='origin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='integracion.inboundevent', verbose_name='evento de origen')),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integracion.subscription', verbose_name='suscripcion')),
            ],
            options={
                'verbose_name': 'evento por avisar',
                'verbose_name_plural': 'eventos por avisar',
                'db_table': 'integracion_outboundevent',
                'ordering': ['-created_at'],
            },
        )),
        SiFalta(migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('creditor', 'url'), name='uq_subscription_url'),
        )),
        SiFalta(migrations.AddIndex(
            model_name='outboundevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='ix_outboundevent_por_enviar'),
        )),
        SiFalta(migrations.AddConstraint(
            model_name='outboundevent',
            constraint=models.UniqueConstraint(fields=('event_id', 'subscription'), name='uq_outboundevent'),
        )),
        SiFalta(migrations.AddConstraint(
            model_name='outboundevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'delivered', 'failed'])), name='ck_outboundevent_status'),
        )),
    ]
