# Generated by Django 6.1.1 on 2026-09-17 02:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=160, verbose_name='razon social')),
                ('trade_name', models.CharField(max_length=120, verbose_name='nombre de fantasia')),
                ('tax_id', models.CharField(help_text='Normalizado, sin puntos y con guion: 76543210-3', max_length=12, unique=True, verbose_name='RUT')),
                ('status', models.CharField(choices=[('onboarding', 'En incorporacion'), ('active', 'Activa'), ('paused', 'Pausada'), ('churned', 'Dada de baja')], default='onboarding', max_length=20, verbose_name='estado')),
                ('client_since', models.DateField(blank=True, null=True, verbose_name='cliente desde')),
                ('commune', models.CharField(blank=True, max_length=80, null=True, verbose_name='comuna')),
                ('region', models.CharField(blank=True, max_length=80, null=True, verbose_name='region')),
                ('website', models.URLField(blank=True, null=True, verbose_name='sitio web')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'empresa acreedora',
                'verbose_name_plural': 'empresas acreedoras',
                'db_table': 'crm_creditor',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identificador')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'rubro',
                'verbose_name_plural': 'rubros',
                'db_table': 'crm_industry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('starts_on', models.DateField(verbose_name='inicio')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='termino')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('running', 'En curso'), ('paused', 'Pausada'), ('finished', 'Finalizada')], default='draft', max_length=20, verbose_name='estado')),
                ('channels', models.JSONField(default=list, verbose_name='canales')),
                ('contact_attempts', models.PositiveSmallIntegerField(default=3, help_text='Cuantas veces se le escribe a cada deudor durante la campana.', verbose_name='intentos de contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crm.creditor', verbose_name='acreedor')),
            ],
            options={
                'verbose_name': 'campana',
                'verbose_name_plural': 'campanas',
                'db_table': 'crm_campaign',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='CreditorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='nombre completo')),
                ('job_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono')),
                ('is_primary', models.BooleanField(default=False, verbose_name='es contacto principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.creditor', verbose_name='acreedor')),
            ],
            options={
                'verbose_name': 'contacto del acreedor',
                'verbose_name_plural': 'contactos del acreedor',
                'db_table': 'crm_creditorcontact',
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='creditor',
            name='industry',
            field=models.ForeignKey(db_column='industry_id', on_delete=django.db.models.deletion.PROTECT, related_name='creditors', to='crm.industry', verbose_name='rubro'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='nombre completo')),
                ('job_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='cargo')),
                ('company_name', models.CharField(max_length=160, verbose_name='empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono')),
                ('estimated_debtor_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='deudores estimados')),
                ('estimated_overdue_clp', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='monto moroso estimado (CLP)')),
                ('current_collection_method', models.CharField(blank=True, choices=[('nadie', 'Hoy nadie la gestiona'), ('llamadas', 'Llamamos por telefono'), ('mensajes', 'Enviamos correos o mensajes a mano'), ('externo', 'Una empresa de cobranza externa'), ('mixto', 'Una mezcla de varias')], max_length=20, null=True, verbose_name='como cobran hoy')),
                ('source', models.CharField(choices=[('form', 'Formulario'), ('assistant', 'Asistente')], default='form', max_length=20, verbose_name='origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('converted', 'Convertido'), ('discarded', 'Descartado')], default='new', max_length=20, verbose_name='estado')),
                ('inquiry_message', models.TextField(blank=True, null=True, verbose_name='mensaje de la consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='assistant.conversation', verbose_name='conversacion')),
                ('converted_creditor', models.ForeignKey(blank=True, db_column='converted_creditor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_leads', to='crm.creditor', verbose_name='acreedor creado')),
                ('industry', models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.industry', verbose_name='rubro')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'db_table': 'crm_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='Siempre el dia 1 del mes.', verbose_name='mes del periodo')),
                ('overdue_bracket', models.CharField(choices=[('1-30', '1 a 30 dias'), ('31-90', '31 a 90 dias'), ('91-120', '91 a 120 dias')], max_length=20, verbose_name='tramo de mora')),
                ('debtor_count', models.PositiveIntegerField(default=0, verbose_name='cantidad de deudores')),
                ('average_debt_clp', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='deuda promedio (CLP)')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='recibida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('creditor', models.ForeignKey(db_column='creditor_id', on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='crm.creditor', verbose_name='acreedor')),
            ],
            options={
                'verbose_name': 'entrega de cartera',
                'verbose_name_plural': 'entregas de cartera',
                'db_table': 'crm_portfoliohandover',
                'ordering': ['-period_month', 'overdue_bracket'],
            },
        ),
        migrations.CreateModel(
            name='CampaignFunnelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField(verbose_name='fecha de corte')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='mensajes enviados')),
                ('messages_delivered', models.PositiveIntegerField(default=0, verbose_name='mensajes entregados')),
                ('messages_opened', models.PositiveIntegerField(default=0, verbose_name='mensajes abiertos')),
                ('replies_received', models.PositiveIntegerField(default=0, verbose_name='respuestas recibidas')),
                ('link_clicks', models.PositiveIntegerField(default=0, verbose_name='clics en el enlace')),
                ('fraud_reports', models.PositiveIntegerField(default=0, verbose_name='reportes de fraude')),
                ('optout_requests', models.PositiveIntegerField(default=0, verbose_name='solicitudes de baja')),
                ('debt_disputes', models.PositiveIntegerField(default=0, verbose_name='deudas disputadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='crm.campaign', verbose_name='campana')),
            ],
            options={
                'verbose_name': 'corte del embudo',
                'verbose_name_plural': 'cortes del embudo',
                'db_table': 'crm_campaignfunnelsnapshot',
                'ordering': ['-measured_on'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'measured_on'), name='uq_snapshot_slot')],
            },
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('creditor', 'name'), name='uq_campaign_name'),
        ),
        migrations.AddConstraint(
            model_name='creditorcontact',
            constraint=models.UniqueConstraint(fields=('creditor', 'email'), name='uq_contact_email'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['status'], name='ix_creditor_status'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['trade_name'], name='ix_creditor_trade'),
        ),
        migrations.AddConstraint(
            model_name='portfoliohandover',
            constraint=models.UniqueConstraint(fields=('creditor', 'period_month', 'overdue_bracket'), name='uq_handover_slot'),
        ),
    ]
