# Generated by Django 6.1.1 on 2026-09-22 18:45

from django.db import migrations, models

from crm.operaciones import SiFalta


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        SiFalta(migrations.AddField(
            model_name='campaignfunnelsnapshot',
            name='payments',
            field=models.PositiveIntegerField(default=0, verbose_name='pagos'),
        )),
        SiFalta(migrations.AddField(
            model_name='campaignfunnelsnapshot',
            name='recovered_clp',
            field=models.PositiveBigIntegerField(default=0, verbose_name='recuperado en pesos'),
        )),
        SiFalta(migrations.AddField(
            model_name='campaignfunnelsnapshot',
            name='recovered_uf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='recuperado en UF'),
        )),
        migrations.AlterField(
            model_name='campaignfunnelsnapshot',
            name='link_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='ingresos al portal'),
        ),
    ]
