# Generated by Django 6.1.1 on 2026-09-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='sesion')),
                ('inferred_audience', models.CharField(blank=True, choices=[('prospect', 'Empresa interesada'), ('debtor', 'Persona con deuda'), ('general', 'General')], max_length=20, null=True, verbose_name='publico inferido')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resuelta')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='inicio')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='ultima actividad')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='navegador')),
            ],
            options={
                'verbose_name': 'conversacion',
                'verbose_name_plural': 'conversaciones',
                'db_table': 'assistant_conversation',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identificador')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('audience', models.CharField(choices=[('prospect', 'Empresa interesada'), ('debtor', 'Persona con deuda'), ('general', 'General')], default='general', max_length=20, verbose_name='publico')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('tiebreak_priority', models.SmallIntegerField(default=100, help_text='Decide cuando dos intenciones puntuan igual. Menor gana.', verbose_name='prioridad de desempate')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'intencion',
                'verbose_name_plural': 'intenciones',
                'db_table': 'assistant_intent',
                'ordering': ['audience', 'tiebreak_priority', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('visitor', 'Visitante'), ('assistant', 'Asistente')], max_length=10, verbose_name='quien habla')),
                ('message_text', models.TextField(verbose_name='texto del mensaje')),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='confianza de la coincidencia')),
                ('answer_engine', models.CharField(blank=True, choices=[('rules', 'Catalogo de reglas'), ('llm', 'Modelo de lenguaje'), ('fallback', 'Respuesta de respaldo')], max_length=10, null=True, verbose_name='motor que respondio')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='tiempo de respuesta (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado')),
                ('conversation', models.ForeignKey(db_column='conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='conversacion')),
                ('intent', models.ForeignKey(blank=True, db_column='intent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='assistant.intent', verbose_name='intencion detectada')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'db_table': 'assistant_message',
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_text', models.CharField(help_text="Sin tildes ni signos. Ej: 'cuanto cuesta'", max_length=200, verbose_name='patron')),
                ('match_weight', models.DecimalField(decimal_places=2, default=1, help_text='3.00 frase completa - 2.00 frase parcial - 1.00 palabra suelta', max_digits=4, verbose_name='peso de coincidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('intent', models.ForeignKey(db_column='intent_id', on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='assistant.intent', verbose_name='intencion')),
            ],
            options={
                'verbose_name': 'patron',
                'verbose_name_plural': 'patrones',
                'db_table': 'assistant_intentpattern',
                'ordering': ['-match_weight', 'pattern_text'],
                'constraints': [models.UniqueConstraint(fields=('intent', 'pattern_text'), name='uq_pattern_text')],
            },
        ),
        migrations.CreateModel(
            name='IntentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='texto de la respuesta')),
                ('display_order', models.SmallIntegerField(default=0, verbose_name='orden de presentacion')),
                ('suggested_action', models.CharField(blank=True, help_text='Lo que la interfaz ofrece junto al texto: show_plans, schedule_demo, verify_with_creditor, show_menu...', max_length=40, null=True, verbose_name='accion sugerida')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('intent', models.ForeignKey(db_column='intent_id', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assistant.intent', verbose_name='intencion')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
                'db_table': 'assistant_intentresponse',
                'ordering': ['intent', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('intent', 'display_order'), name='uq_response_slot')],
            },
        ),
    ]
